import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import type {Member} from '../lib/access';
import type {QuoteRecord} from '../lib/quote-calculator';
const temporary=await mkdtemp(path.join(tmpdir(),'freightskills-quote-test-'));
const original=process.cwd();
process.chdir(temporary);
const {loadQuote,saveQuoteRecord,updateQuoteStatus}=await import('../lib/quotes');
process.chdir(original);
after(()=>rm(temporary,{recursive:true,force:true}));
test('saved quotes and status updates are isolated to the owning member',async()=>{
  const member:Member={id:'quote-test-a',name:'A',email:'a@example.test',role:'owner',plan:'core',admin:false,demo:true,enrolled:true};
  const other={...member,id:'quote-test-b'};
  const record={id:randomUUID(),reference:'QA-ONLY',createdAt:new Date().toISOString(),mode:'LTL',lane:'A to B',customer:'Example',buy:100,sell:120,markup:20,status:'Open',snapshot:{}} as QuoteRecord;
  await saveQuoteRecord(member,record);
  assert.equal((await loadQuote(member,record.id))?.sell,120);
  assert.equal(await loadQuote(other,record.id),null);
  await assert.rejects(updateQuoteStatus(other,record.id,'Won'),/QUOTE_NOT_FOUND/);
  assert.equal((await loadQuote(member,record.id))?.status,'Open');
  await updateQuoteStatus(member,record.id,'Won');
  assert.equal((await loadQuote(member,record.id))?.status,'Won');
});
