import {z} from 'zod';
import {vimeoEmbed} from './rules';
const link=z.string().max(1000).refine(v=>!v||(/^https:\/\//.test(v)&&(()=>{try{return !new URL(v).username&&!new URL(v).password}catch{return false}})()),'Use a secure https link');
export const lessonSchema=z.object({id:z.string().min(1).max(100),title:z.string().trim().min(1).max(180),summary:z.string().max(6000),action:z.string().max(3000),minutes:z.number().int().min(1).max(300),recording:z.enum(['new','existing']),source:z.string().max(300),vimeo:z.string().max(1000).refine(v=>!v||!!vimeoEmbed(v),'Enter a valid Vimeo link'),pdfKey:z.string().refine(v=>!v||/^[0-9a-f-]{36}\.pdf$/.test(v),'Invalid PDF'),agentNote:z.string().max(3000).optional(),ownerNote:z.string().max(3000).optional(),published:z.boolean()}).refine(v=>!v.published||!!v.vimeo,'Add a Vimeo video before publishing');
export const courseSchema=z.object({sections:z.array(z.object({id:z.string().min(1).max(100),title:z.string().trim().min(1).max(180),description:z.string().max(1000),audience:z.enum(['all','owner','agent','optional']),lessons:z.array(lessonSchema).max(200)})).max(50),settings:z.object({gptUrl:link,skoolUrl:link,checkoutUrl:link})}).superRefine((c,ctx)=>{const ids=c.sections.flatMap(s=>[s.id,...s.lessons.map(l=>l.id)]);if(new Set(ids).size!==ids.length)ctx.addIssue({code:'custom',message:'Section and lesson IDs must be unique'})});
export type Course=z.infer<typeof courseSchema>;
export type Lesson=z.infer<typeof lessonSchema>;
export function studentCourse(course:Course,role:string,includeDrafts=false):Course{return {...course,sections:course.sections.filter(s=>['all','optional',role].includes(s.audience)).map(s=>({...s,lessons:s.lessons.filter(l=>includeDrafts||l.published).map(l=>includeDrafts?l:({...l,source:'',recording:'existing' as const}))})).filter(s=>s.lessons.length).sort((a,b)=>{const rank=(s:Course['sections'][number])=>s.id==='section-1'?0:s.audience===role?1:s.audience==='optional'?3:2;return rank(a)-rank(b)})}}
export function completedIds(items:{kind:string;data:Record<string,unknown>}[]){return [...new Set(items.filter(i=>i.kind==='lesson_progress'&&i.data.completed===true).map(i=>String(i.data.lessonId)))]}
