import {NextResponse} from 'next/server';
import {teachingInstructions,checkedAnswer} from '@/lib/gpt-prompt';
import {z} from 'zod';
import {requireMember,checkOrigin} from '@/lib/access';
import {approvedSources,retrieve} from '@/lib/knowledge';
import {reserve,settle,usage} from '@/lib/ai-budget';
import {getCourse,studentCourse} from '@/lib/teaching';
const enabled=()=>process.env.AI_ENABLED==='true'&&!!process.env.OPENAI_API_KEY;
export async function GET(){try{const m=await requireMember();return NextResponse.json({enabled:enabled()&&!m.demo,...(!m.demo?await usage(m.id):{remaining:100,dailyRemaining:10}),admin:m.admin},{headers:{'Cache-Control':'no-store'}})}catch{return NextResponse.json({error:'Sign in to use Freightskills GPT.'},{status:401})}}
export async function POST(r:Request){let reservation:string|undefined;try{await checkOrigin();const m=await requireMember();if(!enabled()||m.demo)return NextResponse.json({error:'AI answers are not enabled yet. Your course is available while we finish setup.'},{status:503});const raw=await r.text();if(Buffer.byteLength(raw)>10000)throw Error('Please shorten your question.');const {question}=z.object({question:z.string().trim().min(3).max(2000)}).strict().parse(JSON.parse(raw));const found=retrieve(question,await approvedSources(m));if(!found.length)return NextResponse.json({answer:'I couldn’t find enough relevant teaching in the available library to answer this as Luis would. Try naming the freight topic or lesson, or ask in the community.',sources:[],...await usage(m.id)});
const instructions=teachingInstructions(m.role);
const input=JSON.stringify({question,teaching:found.map(({id,title,text})=>({id,title,text}))});if(Buffer.byteLength(input+instructions)>30000)throw Error('Please ask a shorter, more focused question.');reservation=await reserve(m.id);
const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-4.1-mini-2025-04-14',instructions,input,max_output_tokens:1500,store:false}),signal:AbortSignal.timeout(45000)});if(!response.ok)throw Error('The assistant could not answer right now. Please try again later.');const data=await response.json();await settle(reservation,'complete',data.usage?.input_tokens,data.usage?.output_tokens);reservation=undefined;const answer=checkedAnswer((data.output||[]).flatMap((o:{content?:{type:string;text?:string}[]})=>o.content||[]).filter((c:{type:string})=>c.type==='output_text').map((c:{text:string})=>c.text).join('\n'));if(!answer)throw Error('No answer was returned. Please try again later.');const course=await getCourse(m);const available=studentCourse(course,m.role,m.admin);const links=[...new Map(found.filter(s=>new RegExp('\\b'+s.id+'\\b').test(answer)).map(s=>{const lesson=course.sections.flatMap(s=>s.lessons).filter(l=>available.sections.some(s=>s.lessons.some(a=>a.id===l.id))).find(l=>l.source.includes(s.id==='approved-objection'?'C019':s.id));return [s.id,{id:s.id,title:s.title,href:lesson?'/learn/'+lesson.id:null}]})).values()];return NextResponse.json({answer,sources:links,...await usage(m.id)},{headers:{'Cache-Control':'no-store'}})
}catch(e){if(reservation)await settle(reservation,'failed').catch(()=>{});return NextResponse.json({error:e instanceof Error&&!(e instanceof z.ZodError)?e.message:'Please enter a question of 3–2,000 characters.'},{status:400})}}
