import {NextResponse} from 'next/server';
import {z} from 'zod';
import {requireMember,checkOrigin} from '@/lib/access';
import {listItems,saveItem,deleteItem} from '@/lib/store';
import {gradeQuote} from '@/lib/rules';
import {lessonById} from '@/lib/catalog';
const schema=z.object({kind:z.enum(['profile','prospect','playbook','progress','attempt']),id:z.uuid().optional(),data:z.record(z.string(),z.unknown())});
function failure(e:unknown){const message=e instanceof Error?e.message:'Unable to save';return NextResponse.json({error:message},{status:message==='UNAUTHENTICATED'?401:message==='FORBIDDEN'||message==='ENROLLMENT_REQUIRED'?403:400})}
export async function GET(){try{return NextResponse.json(await listItems(await requireMember()),{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(request:Request){try{await checkOrigin();const m=await requireMember();if(Number(request.headers.get('content-length')||0)>65000)throw Error('Entry is too large');const raw=await request.text();if(raw.length>65000)throw Error('Entry is too large');const {kind,id,data}=schema.parse(JSON.parse(raw));if(kind==='profile'){z.object({role:z.enum(['agent','owner']),name:z.string().min(1).max(80)}).parse(data)}if(kind==='prospect'){z.object({company:z.string().min(1).max(160),contact:z.string().max(160),stage:z.enum(['Research','Contacted','Conversation','Quote opportunity','Customer']),nextAction:z.string().max(500),notes:z.string().max(5000),due:z.string().max(10)}).parse(data)}if(kind==='playbook'){z.object({title:z.string().min(1).max(160),content:z.string().min(1).max(30000)}).passthrough().parse(data)}if(kind==='progress'){const parsed=z.object({lessonId:z.string(),status:z.literal('in_progress')}).parse(data);if(!lessonById(parsed.lessonId))throw Error('Unknown lesson')}if(kind==='attempt'){const a=z.object({lessonId:z.literal('5.3'),fields:z.array(z.string()).max(10),price:z.number(),draft:z.string().max(5000)}).parse(data);data.feedback=gradeQuote(a)}const savedId=await saveItem(m,kind,data,id);return NextResponse.json({id:savedId,feedback:data.feedback})}catch(e){return failure(e)}}
export async function DELETE(request:Request){try{await checkOrigin();const m=await requireMember();const {id}=z.object({id:z.uuid()}).parse(await request.json());await deleteItem(m,id);return NextResponse.json({ok:true})}catch(e){return failure(e)}}
